name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install system dependencies (Linux)
        run: sudo apt update && sudo apt-get install -y libev-dev libgmp-dev libssl-dev pkg-config
        if: runner.os == 'Linux'

      - name: Install system dependencies (macOS)
        run: brew install libev gmp openssl@3 pkg-config
        if: runner.os == 'macOS'

      - name: Setup Dune
        uses: ocaml-dune/setup-dune@v1
        with:
          version: latest

      - name: Lock dependencies
        run: dune pkg lock

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest
